security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateur : récupération depuis la base de données en utilisant l'email
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Configuration du firewall principal pour gérer la connexion et la déconnexion
        main:
            # Authentification via un formulaire
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home  # Redirection après connexion réussie
                username_parameter: email
                password_parameter: password

            provider: app_user_provider
            logout:
                path: app_logout
                # Cette route sera utilisée pour la déconnexion

          

    # Access Control : règles d'accès pour différentes pages
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # Seuls les admins peuvent accéder à cette section
        - { path: ^/profile, roles: ROLE_USER }  # Accès au profil pour tous les utilisateurs (ROLE_USER)
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Laisser l'accès libre à la page de connexion
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Laisser l'accès libre à la page d'inscription

